services:
  react:
    build: ./react-client
    ports:
     - 3000:3000

  express:
    build:
      context: ./
      dockerfile: ./express-server
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
      react:
        condition: service_started
