services:
  postgres:
    image: postgres:latest
    command: "-c log_connections=true"
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./express-server/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  react:
    build: ./react-client
    ports:
     - 3000:3000

  express:
    build: ./express-server
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
      react:
        condition: service_started

volumes:
  postgres-data:
